IF (OBJECT_ID('T_RESERVE', 'tr') IS NOT  NULL)
    DROP TRIGGER T_RESERVE
GO

CREATE TRIGGER T_RESERVE ON RESERVE
	FOR INSERT,UPDATE,DELETE
AS
	DECLARE @_A INT;
	DECLARE @_B INT;
	SET @_A = (SELECT COUNT(ROOM_STATUS_ID) FROM ROOM_INFO WHERE ROOM_ID IN (SELECT INSERTED.ROOM_ID FROM INSERTED));
	SET @_B = (SELECT COUNT(ROOM_STATUS_ID) FROM ROOM_INFO WHERE ROOM_ID IN (SELECT INSERTED.ROOM_ID FROM INSERTED) AND ROOM_STATUS_ID = 1);
	IF @_A = @_B 
	BEGIN
		UPDATE ROOM_INFO SET ROOM_STATUS_ID = 3 WHERE ROOM_ID IN (SELECT INSERTED.ROOM_ID  FROM INSERTED);
		UPDATE ROOM_INFO SET ROOM_STATUS_ID = 1 WHERE ROOM_ID IN (SELECT DELETED.ROOM_ID  FROM DELETED);
	END
	ELSE
	BEGIN
		SELECT '≤Â»Î ß∞‹';
		ROLLBACK;
	END