IF (OBJECT_ID('T_CHECKOUT', 'tr') IS NOT  NULL)
    DROP TRIGGER T_CHECKOUT
GO

CREATE TRIGGER T_CHECKOUT ON CHECKOUT
	FOR INSERT
AS
	DECLARE @_A INT;
	DECLARE @_B INT;
	SET @_A = 
	(
		SELECT COUNT(ROOM_STATUS_ID) FROM ROOM_INFO WHERE ROOM_ID IN
		(SELECT ROOM_ID FROM CHECKIN WHERE CHECKIN_ID IN (SELECT INSERTED.CHECKIN_ID FROM INSERTED))
	)
	SET @_B = 
	(	
		SELECT COUNT(ROOM_STATUS_ID) FROM ROOM_INFO WHERE ROOM_ID IN
		(SELECT ROOM_ID FROM CHECKIN WHERE CHECKIN_ID IN (SELECT INSERTED.CHECKIN_ID FROM INSERTED))
		AND ROOM_STATUS_ID = 4
		
	)
	/** 退房均为占用*/
	IF(@_A = @_B)
	BEGIN
		/** 更新房间状态*/
		UPDATE ROOM_INFO SET ROOM_STATUS_ID = 2 WHERE ROOM_ID IN (
			SELECT CHECKIN.ROOM_ID  FROM INSERTED
			LEFT JOIN CHECKIN ON INSERTED.CHECKIN_ID = CHECKIN.CHECKIN_ID
		);
	END
	ELSE
	BEGIN
		SELECT '退房失败！';
		ROLLBACK;
	END

