IF (OBJECT_ID('T_CHECKIN', 'tr') IS NOT  NULL)
    DROP TRIGGER T_CHECKIN
GO
/** ��ס���Ĵ����� */
CREATE TRIGGER T_CHECKIN ON CHECKIN
	FOR INSERT,UPDATE,DELETE
AS
	DECLARE @_A INT;
	DECLARE @_B INT;
	SET @_A = (SELECT COUNT(ROOM_STATUS_ID) FROM ROOM_INFO WHERE ROOM_ID IN (SELECT INSERTED.ROOM_ID FROM INSERTED));
	SET @_B = (SELECT COUNT(ROOM_STATUS_ID) FROM ROOM_INFO WHERE ROOM_ID IN (SELECT INSERTED.ROOM_ID FROM INSERTED) AND ROOM_STATUS_ID = 1);
	/** �ж���ס�ķ����Ϊ���� */
	IF @_A = @_B 
	BEGIN
		/** ���ڸ����µ�����Ϊ4(ռ��)���ɵ�����Ϊ1(����) */
		/** ���ڲ�������Ϊ4(ռ��) */
		UPDATE ROOM_INFO SET ROOM_STATUS_ID = 4 WHERE ROOM_ID IN (SELECT INSERTED.ROOM_ID  FROM INSERTED);
		/** ���ڸ��º�ɾ������Ϊ2(Ԥ��) */
		UPDATE ROOM_INFO SET ROOM_STATUS_ID = 2 WHERE ROOM_ID IN (SELECT DELETED.ROOM_ID  FROM DELETED);
	END
	ELSE
	BEGIN
		SELECT '����ʧ�ܣ�';
		ROLLBACK;
	END