IF EXISTS (select * from sysobjects where type = 'P' and name = 'P_GROUP_CHECKIN')
    DROP PROCEDURE P_GROUP_CHECKIN;
GO

CREATE PROCEDURE P_GROUP_CHECKIN 
	@NAME VARCHAR(20), 
	@IDCARD VARCHAR(18),
	@ROOM_ID INT,
	@DAY INT
AS
BEGIN
	DECLARE @GROUP_CHECKIN_ID INT;
	IF OBJECT_ID('GROUP_CHECKIN') IS NULL
	BEGIN
		CREATE TABLE GROUP_CHECKIN
		(
		GROUP_CHECKIN_ID INT PRIMARY KEY,
		GROUP_CHECKIN_NAME VARCHAR(20) NOT NULL,
		GROUP_CHECKIN_IDCARD VARCHAR(18) NOT NULL,
		GROUP_CHECKIN_ROOM_ID INT FOREIGN KEY REFERENCES ROOM_INFO,
		GROUP_CHECKIN_DAY INT CHECK(GROUP_CHECKIN_DAY>0)
		)
		SET @GROUP_CHECKIN_ID = 1;
	END
	ELSE
	BEGIN
		SELECT @GROUP_CHECKIN_ID = MAX(GROUP_CHECKIN_ID) + 1 FROM GROUP_CHECKIN;
	END

	IF  @NAME IS NOT NULL AND LEN(@IDCARD) = 18 AND @ROOM_ID IN (SELECT @ROOM_ID FROM ROOM_INFO WHERE ROOM_STATUS_ID = 1) 
	AND @DAY > 0
	BEGIN
		INSERT INTO GROUP_CHECKIN VALUES(@GROUP_CHECKIN_ID,@NAME,@IDCARD,@ROOM_ID,@DAY);
	END
	ELSE
	BEGIN
		SELECT '输入参数有问题！';
	END
END
